"""
spectral_operators.evolution
============================

Evolution operators and propagators.

This module provides matrix-exponential propagators for unitary-style
and semigroup evolution generated by immutable LinearOperator objects.
"""

from __future__ import annotations

from numbers import Real

import numpy as np
from scipy.linalg import expm

from .core.algebra import LinearOperator
from .core.exceptions import (
    DimensionMismatchError,
    NonSquareOperatorError,
    OperatorError,
)
from .core.utilities import as_one_dimensional_array


# ===========================================================================
# Shared Helpers
# ===========================================================================

def _validate_operator(
    operator: LinearOperator,
) -> LinearOperator:
    """
    Validate and return a square LinearOperator.
    """

    if not isinstance(operator, LinearOperator):
        raise OperatorError(
            "operator must be a LinearOperator."
        )

    if not operator.is_square:
        raise NonSquareOperatorError(
            "Evolution propagators require square operators."
        )

    return operator


def _validate_time(
    t,
    *,
    name: str = "t",
):
    """
    Validate a finite scalar evolution parameter.
    """

    if isinstance(t, bool) or not np.isscalar(t):
        raise OperatorError(
            f"{name} must be a scalar."
        )

    if not np.isfinite(t):
        raise OperatorError(
            f"{name} must be finite."
        )

    return t


# ===========================================================================
# Propagators
# ===========================================================================

class Propagator:
    """
    Base class for matrix-exponential propagators.

    Parameters
    ----------
    operator
        Square LinearOperator generating the evolution.
    """

    def __init__(
        self,
        operator: LinearOperator,
    ):
        object.__setattr__(
            self,
            "operator",
            _validate_operator(operator),
        )

    def apply(
        self,
        vector,
        t,
    ) -> np.ndarray:
        """
        Apply the propagator at time ``t`` to a state vector.
        """

        state = as_one_dimensional_array(
            vector,
            name="vector",
            copy=True,
        )

        if len(state) != self.operator.cols:
            raise DimensionMismatchError(
                "vector dimension does not match operator dimension."
            )

        return self.matrix(t) @ state

    def matrix(
        self,
        t,
    ) -> np.ndarray:
        """
        Return the propagator matrix at time ``t``.
        """

        raise NotImplementedError(
            "Propagator subclasses must implement matrix()."
        )


# ===========================================================================
# Unitary Evolution
# ===========================================================================

class UnitaryEvolution(Propagator):
    """
    Evolution generated by

        U(t) = exp(-i H t).

    Notes
    -----
    The resulting propagator is unitary when the generator ``H`` is
    Hermitian. This class does not automatically enforce Hermiticity.
    """

    def matrix(
        self,
        t,
    ) -> np.ndarray:
        """
        Return ``exp(-i H t)``.
        """

        t = _validate_time(t)

        return expm(
            -1j * self.operator.matrix * t
        )

    def is_unitary(
        self,
        t,
        *,
        tol: float = 1e-10,
    ) -> bool:
        """
        Check whether the propagator is numerically unitary.
        """

        propagator = self.matrix(t)
        identity = np.eye(
            propagator.shape[0],
            dtype=propagator.dtype,
        )

        return bool(
            np.allclose(
                propagator.conj().T @ propagator,
                identity,
                atol=tol,
                rtol=tol,
            )
        )


# ===========================================================================
# Semigroup Evolution
# ===========================================================================

class SemigroupEvolution(Propagator):
    """
    Evolution generated by

        S(t) = exp(t A).

    This form is commonly used for diffusion, heat flow, dissipative
    systems, and Markov-style dynamics.
    """

    def matrix(
        self,
        t,
    ) -> np.ndarray:
        """
        Return ``exp(t A)``.
        """

        t = _validate_time(t)

        return expm(
            t * self.operator.matrix
        )


# ===========================================================================
# Evolution Analyzer
# ===========================================================================

class EvolutionAnalyzer:
    """
    High-level interface for operator-induced evolution.
    """

    def __init__(
        self,
        operator: LinearOperator,
    ):
        object.__setattr__(
            self,
            "operator",
            _validate_operator(operator),
        )

    def propagate_semigroup(
        self,
        vector,
        t,
    ) -> np.ndarray:
        """
        Apply semigroup evolution to a vector.
        """

        return self.semigroup().apply(
            vector,
            t,
        )

    def propagate_unitary(
        self,
        vector,
        t,
    ) -> np.ndarray:
        """
        Apply unitary-style evolution to a vector.
        """

        return self.unitary().apply(
            vector,
            t,
        )

    def semigroup(
        self,
    ) -> SemigroupEvolution:
        """
        Return a semigroup propagator.
        """

        return SemigroupEvolution(
            self.operator
        )

    def unitary(
        self,
    ) -> UnitaryEvolution:
        """
        Return a unitary-style propagator.
        """

        return UnitaryEvolution(
            self.operator
        )
